# Generated by Django 6.0 on 2026-09-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_salarypayment_shift_treasurytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('credit_card', 'بطاقة مصرفية'), ('debt', 'آجل'), ('online_wallet', 'محفظة إلكترونية'), ('other', 'أخرى')], default='cash', max_length=20),
        ),
    ]
