# Generated by Django 6.0 on 2026-09-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
