# Generated by Django 6.0 on 2026-09-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد التجهيز'), ('ready', 'جاهز للتسليم'), ('delivered', 'تم التسليم'), ('paid', 'مدفوع'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='pending', max_length=20),
        ),
    ]
