// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/24/2025, 11:09:22 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["E:/restaurants/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/restaurants/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/restaurants/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/restaurants/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/restaurants/frontend/plugins/**/*.{js,ts,mjs}","E:/restaurants/frontend/composables/**/*.{js,ts,mjs}","E:/restaurants/frontend/utils/**/*.{js,ts,mjs}","E:/restaurants/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/restaurants/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/restaurants/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/restaurants/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;