# Generated by Django 6.0 on 2025-12-13 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=10, unique=True)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('status', models.CharField(choices=[('available', 'شاغرة'), ('occupied', 'مشغولة'), ('reserved', 'محجوزة'), ('cleaning', 'تحتاج تنظيف')], default='available', max_length=20)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('current_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_assigned_to_current_order', to='orders.order')),
            ],
            options={
                'verbose_name': 'طاولة',
                'verbose_name_plural': 'طاولات',
                'ordering': ['table_number'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('reservation_time', models.DateTimeField()),
                ('number_of_guests', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('confirmed', 'مؤكد'), ('pending', 'قيد الانتظار'), ('cancelled', 'ملغى'), ('completed', 'انتهى')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='reservations.table')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'حجوزات',
                'ordering': ['reservation_time'],
            },
        ),
    ]
