# Generated by Django 6.0 on 2026-02-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='unit_of_measure',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('KG', 'كيلوجرام'), ('Liter', 'لتر'), ('Piece', 'قطعة/وحدة')], default='Piece', max_length=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='current_stock',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='reorder_level',
            field=models.FloatField(default=0.0),
        ),
    ]
