# Generated by Django 6.0 on 2025-12-10 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit_of_measure', models.CharField(choices=[('kg', 'كيلوجرام'), ('liter', 'لتر'), ('pcs', 'قطعة/وحدة'), ('box', 'علبة'), ('g', 'جرام'), ('ml', 'مليلتر')], default='pcs', max_length=10)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'مكون',
                'verbose_name_plural': 'المخزون (المكونات)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_using_this', to='inventory.ingredient')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'مكون وصفة',
                'verbose_name_plural': 'مكونات الوصفات',
                'unique_together': {('menu_item', 'ingredient')},
            },
        ),
    ]
