# Generated by Django 6.0 on 2025-12-13 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('waiter', 'نادل'), ('chef', 'طاهٍ'), ('manager', 'مدير'), ('cashier', 'كاشير'), ('other', 'أخرى')], default='waiter', max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'موظفون',
            },
        ),
    ]
