# Generated by Django 6.0 on 2026-09-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
