# Generated by Django 6.0 on 2026-02-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Restaurant', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurant/')),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('invoice_footer_message', models.TextField(blank=True, default='Thank you for your visit!', null=True)),
                ('is_online_ordering_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'إعدادات المطعم',
                'verbose_name_plural': 'إعدادات المطعم',
            },
        ),
    ]
