# Generated by Django 6.0 on 2026-02-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantsettings',
            old_name='is_online_ordering_enabled',
            new_name='is_delivery_enabled',
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='default_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='invoice_footer_message',
            field=models.TextField(blank=True, default='شكراً لزيارتكم!', null=True),
        ),
    ]
